dotfiles/:
 home:
  from:
   ~/
  files:
   - .Xresources*
   - .bashrc
   - .xprofile
 script:
  from:
   ~/.script/
  files:
   - "*"
 picom:
  from:
   ~/.config/
  files:
   picom.conf
 i3:
  from:
   ~/.config/i3/
  files:
   - "*"
 rofi:
  from:
   ~/.config/rofi/
  files:
   - config.rasi
 zsh:
  from:
   ~/
  files:
   - .zshrc
   - .zshenv
   - .env
 urxvt:
  from:
   ~/.config/urxvt/
  files:
   - "*"
   - themes/*
 vim:
  from:
   ~/
  files:
   - .vimrc
 idea:
  from:
   ~/
  files:
   - .ideavimrc
 htop:
  from:
   ~/.config/htop/
  files:
   - htoprc
 polybar:
  from:
   ~/.config/polybar/
  files:
   - config
 vifm:
  from:
   ~/.config/vifm/
  files:
   - vifmrc
   - colors/*
 xkeysnail:
  from:
   ~/.config/xkeysnail/
  files:
   - main.py
 zathura:
  from:
   ~/.config/zathura/
  files:
   - zathurarc
 feh:
  from:
   ~/.config/feh/
  files:
   - keys
 dunst:
  from:
   ~/.config/dunst/
  files:
   - dunstrc
 neofetch:
  from:
   ~/.config/neofetch/
  files:
   - config.conf
 vimium:
  from:
   ~/.config/vimium/
  files:
    - "*"
 firefox:
  from:
   ~/.mozilla/firefox/p9xhtcus.default-release/chrome/
  files:
   - userChrome.css
 newsboat:
  from:
   ~/.newsboat/
  files:
   - config
 kbmap:
  from:
   ~/.config/kbmap/
  files:
   - config.py

