dotfiles/:
 home:
  from:
   ~/
  files:
   - .Xresources*
   - .bashrc
   - .xprofile
 script:
  from:
   ~/.script/
  files:
   - "*"
 compton:
  from:
   ~/.config/
  files:
   compton.conf
 i3:
  from:
   ~/.config/i3/
  files:
   - "*"
 rofi:
  from:
   ~/.config/rofi/
  files:
   - config.rasi
 zsh:
  from:
   ~/
  files:
   - .zshrc
 urxvt:
  from:
   ~/.config/urxvt/
  files:
   - config
   - themes/*
 vim:
  from:
   ~/
  files:
   - .vimrc
 htop:
  from:
   ~/.config/htop/
  files:
   - htoprc
 kbmap:
  from:
   ~/.config/kbmap/
  files:
   - config.py
 polybar:
  from:
   ~/.config/polybar/
  files:
   - config
 vifm:
  from:
   ~/.config/vifm/
  files:
   - vifmrc
   - colors/*
 xkeysnail:
  from:
   ~/.config/xkeysnail/
  files:
   - configs/main.py
 zathura:
  from:
   ~/.config/zathura/
  files:
   - zathurarc
 feh:
  from:
   ~/.config/feh/
  files:
   - keys

