#!/bin/sh

BRIGHTNESS_PATH="/sys/class/backlight/intel_backlight/actual_brightness"
CURRENT="$(cat $BRIGHTNESS_PATH)"
NEXT=$(($CURRENT+$1))

if [ $NEXT -lt 1 ]; then
	exit 1
fi
echo $NEXT > /sys/class/backlight/intel_backlight/brightness
echo `cat $BRIGHTNESS_PATH`
