#!/bin/bash

MAC="00:A4:1C:04:E1:9D"

bluetoothctl power on

bluetoothctl disconnect $MAC

while true; do
    STATUS=$(bluetoothctl info $MAC | grep "Connected: yes")

    if [ -z "$STATUS" ]; then
        break
    fi

    sleep 1
done

bluetoothctl connect $MAC
