#!/bin/sh

# xrandr's name for the external monitor connection
DEFAULT=eDP-1-1

# if monitor found
if (xrandr --query | grep -q "^DP-1-1 connected"); then
    echo "detected DP-1-1"
	xrandr --output "$DEFAULT" --off
	xrandr --output "DP-1-1" --auto --primary
elif (xrandr --query | grep -q "^HDMI-1-1 connected"); then
	echo "detected HDMI-1-1"
	xrandr --output "$DEFAULT" --off
	xrandr --output "HDMI-1-1" --auto --primary
else
	echo "detected $DEFAULT"
	xrandr --output "$DEFAULT" --auto --primary
	xrdb -merge ~/.Xresources4k
fi
