#!/bin/sh

# xrandr's name for the external monitor connection
DEFAULT=eDP-1
MONITOR=HDMI-1

# if monitor found
if xrandr --query | grep -q "^$MONITOR connected"; then
	echo "detect ^$MONITOR"
	xrandr --output "$DEFAULT" --off
	xrandr --output "$MONITOR" --auto --primary
else
	xrandr --output "$MONITOR" --off
	xrandr --output "$DEFAULT" --auto --primary
	xrdb -merge ~/.Xresources4k
fi
