#!/usr/bin/sh

ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i Кухня\ \(2012\)\ -\ S1E01\ -\ WEB-DL\ 1080p.mkv -vf "setpts=PTS/1.4" -filter:a "atempo=1.4" -c:v h264_vaapi output.mkv
