#!/usr/bin/env sh
# echo "https://api.github.com/search/code?q=language:$1+$2"
curl\
    -H "Authorization: token $GHCS_TOKEN"\
    -H "Accept: application/vnd.github.v3+json"\
    "https://api.github.com/search/code?q=language:$1+$2"\
    | jq '[.items[] | {repo: .repository.full_name, path: .path, url: .html_url}]'
