#!/bin/sh

# apply xresources
xrdb ~/.Xresources

~/.script/displays

# set default pulseaudio profile
pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo 

# composer
run-if-not picom $(picom --config ~/.config/picom.conf -b) &

# disable Caps Lock default behavior
sleep 1 && setxkbmap -option caps:none

~/.script/system/xinput &
~/.script/system/xset &
~/.script/system/onlog &
~/.script/system/autorun &
