#!/bin/sh

# apply xresources
xrdb ~/.Xresources

# display config
~/.script/displays

# set default pulseaudio profile
pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo &

# disable Caps Lock default behavior
setxkbmap -option caps:none

# autorun
~/.script/system/xinput &
~/.script/system/xset &
~/.script/system/onlog &
~/.script/system/autorun &
