#!/bin/sh

# apply xresources
xrdb ~/.Xresources

# xrandr's name for the external monitor connection
DEFAULT=eDP-1
MONITOR=HDMI-1

# if monitor found
if xrandr --query | grep -q "^$MONITOR connected"; then
	echo "detect ^$MONITOR"
	xrandr --output "$DEFAULT" --off
	xrandr --output "$MONITOR" --primary
else
	xrandr --output "$MONITOR" --off
	xrandr --output "$DEFAULT" --auto --primary
	xrdb -merge ~/.Xresources4k

	# Fix GTK3 icon size
	export GDK_SCALE=2
	export GDK_DPI_SCALE=0.5
fi

# composer
compton --config ~/.config/compton.conf -b

# keyboard mapping
killall -w -9 xkeysnail, 1 2> /dev/null
xkeysnail -q ~/.config/xkeysnail/configs/main.py &
# set keyboard layout and disable Caps Lock default behavior
sleep 1 && setxkbmap -layout us,ru -option 'grp:ctrl_shift_toggle' -option caps:none

# usb mouse settings
xinput set-prop "A4TECH USB Device" "libinput Accel Profile Enabled" 0, 1 2> /dev/null

# touchpad behavior
xinput --set-prop "DLL07BE:01 06CB:7A13 Touchpad" "Synaptics Scrolling Distance" -50, -50

# disable screen timeout and screensaver
xset s off
xset -dpms
xset s noblank

# set keyboard delay and repeat
xset r rate 220 20

# autostart
thyme-track.sh ~/thyme-track.json ~/thyme-report.html &
