#!/bin/sh

# apply xresources
xrdb ~/.Xresources

# set default pulseaudio profile
pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo 

# composer
compton --config ~/.config/picom.conf -b

# keyboard mapping
killall -9 xkeysnail
xkeysnail -q ~/.config/xkeysnail/main.py &

# set keyboard layout and disable Caps Lock default behavior
sleep 1 && setxkbmap -option caps:none

# mouse config
xinput set-prop "Logitech Wireless Mouse" "libinput Accel Speed" "-0.6"

# disable screen timeout and screensaver
xset s off
xset -dpms
xset s noblank

# set keyboard delay and repeat
xset r rate 220 20

# run notification daemon
killall -9 dunst
dunst &

# auto hide mouse
unclutter -idle 2 -noevents &
