#!/usr/bin/env sh

# Terminate already running bar instances
killall -wq -9 polybar

# Launch polybar based on screen
xrandr | grep 'HDMI-1 connected' && polybar main &
xrandr | grep 'HDMI-1 disconnected' && polybar main4k &

# Hide bar by default
sleep 1.3 && polybar-msg cmd hide

