#!/usr/bin/env sh

notify-send -u low "Brightness: `~/.script/wm/backlight +50`"
NEW=`ddccontrol dev:/dev/i2c-8 -r 0x10 -W +10 2>/dev/null | awk '/^Control/{print $3}' | awk -F '/' '{print $2}'`
notify-send -u low "Brightness: $NEW"

