#!/usr/bin/env sh

maim -su | xclip -selection clipboard -t image/png && xclip -selection clipboard -t image/png -o > ~/picture/screenshot/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png
notify-send -u low "Screenshot"
