#!/bin/sh

# apply xresources
xrdb ~/.Xresources

# display config
~/.script/displays

# disable Caps Lock default behavior
setxkbmap -option caps:none

# autorun
~/.script/system/xinput &
~/.script/system/xset &
~/.script/system/onlog &
~/.script/system/autorun &
