#!/bin/sh

# usb mouse settings
xinput set-prop "pointer:Compx 2.4G Receiver"     "libinput Accel Profile Enabled" 0 0, 1 2> /dev/null
xinput set-prop "Logitech G403 HERO Gaming Mouse" "libinput Accel Profile Enabled" 0, 1 2> /dev/null
xinput set-prop "Logitech G703 LIGHTSPEED Wireless Gaming Mouse w/ HERO" "libinput Accel Profile Enabled" 0, 1 2> /dev/null

# touchpad behavior
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad"   "libinput Tapping Enabled" "1"
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad"   "libinput Natural Scrolling Enabled" "1"
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad"   "libinput Accel Speed" "0.2"

xinput set-prop "Ploopy Corporation Trackball Nano Mouse" "libinput Accel Profile Enabled" 0, 1
