#!/bin/sh

# usb mouse settings
xinput set-prop "pointer:Compx 2.4G Receiver"                            "libinput Accel Profile Enabled" 0 1 0
xinput set-prop "Logitech G403 HERO Gaming Mouse"                        "libinput Accel Profile Enabled" 0 1 0
xinput set-prop "Logitech G703 LIGHTSPEED Wireless Gaming Mouse w/ HERO" "libinput Accel Profile Enabled" 0 1 0
xinput set-prop "pointer:Logitech G703 LS"                               "libinput Accel Profile Enabled" 0 1 0

# touchpad behavior
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad"   "libinput Tapping Enabled" "1"
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad"   "libinput Natural Scrolling Enabled" "1"
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad"   "libinput Accel Speed" "0.2"
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad"   "libinput Scrolling Pixel Distance" "40"

xinput set-prop "Ploopy Corporation Trackball Nano Mouse" "libinput Accel Profile Enabled" 0 1 0
